import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'Inter', 'system-ui', '-apple-system', 'sans-serif'],
        serif: ['Playfair Display', 'Cormorant Garamond', 'Georgia', 'serif'],
        display: ['Playfair Display', 'Plus Jakarta Sans', 'serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      colors: {
        // Editorial Local Discovery Exact Tokens
        surface: {
          DEFAULT: '#faf9f4',
          dim: '#dbdad5',
          bright: '#faf9f4',
          lowest: '#ffffff',
          'container-lowest': '#ffffff',
          'container-low': '#f5f4ef',
          container: '#efeee9',
          'container-high': '#e9e8e3',
          'container-highest': '#e3e3de',
          variant: '#e3e3de',
          tint: '#635f3a',
        },
        'on-surface': {
          DEFAULT: '#1b1c19',
          variant: '#49473c',
        },
        'inverse-surface': {
          DEFAULT: '#30312e',
          'on': '#f2f1ec',
        },
        outline: {
          DEFAULT: '#7a776b',
          variant: '#cbc6b8',
        },
        primary: {
          DEFAULT: '#54512d',
          on: '#ffffff',
          container: '#6d6943',
          'on-container': '#f0e9ba',
          inverse: '#cec89b',
          fixed: '#eae4b5',
          'fixed-dim': '#cec89b',
          'on-fixed': '#1f1c01',
          'on-fixed-variant': '#4b4825',
          glow: 'rgba(84, 81, 45, 0.25)',
          faint: 'rgba(84, 81, 45, 0.08)',
          light: '#6d6943',
          dark: '#3f3d22',
        },
        secondary: {
          DEFAULT: '#6e5a51',
          on: '#ffffff',
          container: '#f8ddd1',
          'on-container': '#746057',
          fixed: '#f8ddd1',
          'fixed-dim': '#dbc1b6',
          'on-fixed': '#261811',
          'on-fixed-variant': '#55433b',
        },
        tertiary: {
          DEFAULT: '#664754',
          on: '#ffffff',
          container: '#805e6d',
          'on-container': '#ffdfeb',
          fixed: '#ffd8e7',
          'fixed-dim': '#e4bbcc',
          'on-fixed': '#2c1420',
          'on-fixed-variant': '#5c3e4c',
        },
        error: {
          DEFAULT: '#ba1a1a',
          on: '#ffffff',
          container: '#ffdad6',
          'on-container': '#93000a',
        },
        // Editorial brand aliases
        olive: {
          DEFAULT: '#54512d',
          50: '#f7f6ed',
          100: '#f0e9ba',
          200: '#cec89b',
          300: '#8c8758',
          400: '#6d6943',
          500: '#54512d',
          600: '#3f3d22',
          700: '#2b2a17',
        },
        espresso: {
          DEFAULT: '#48372f',
          50: '#fdfcfb',
          100: '#f5f4ef',
          200: '#e3e3de',
          300: '#746057',
          400: '#6e5a51',
          500: '#48372f',
          600: '#3d2d26',
          700: '#1b1c19',
          800: '#120e0b',
        },
        mauve: {
          DEFAULT: '#805e6d',
          50: '#fff5f8',
          100: '#ffdfeb',
          200: '#ffd8e7',
          300: '#e4bbcc',
          400: '#c8a1b1',
          500: '#805e6d',
          600: '#664754',
          700: '#4a2f3c',
        },
        ivory: {
          DEFAULT: '#faf9f4',
          50: '#ffffff',
          100: '#faf9f4',
          200: '#f5f4ef',
          300: '#efeee9',
          400: '#e9e8e3',
          500: '#e3e3de',
          600: '#dbdad5',
        },
        bg: {
          DEFAULT: 'var(--bg)',
          subtle: 'var(--bg-subtle)',
          elevated: 'var(--bg-elevated)',
          surface: 'var(--bg-surface)',
          card: 'var(--bg-card)',
          card2: 'var(--bg-card2)',
          cardHover: 'var(--bg-card-hover)',
          header: 'var(--bg-header)',
          nav: 'var(--bg-nav)',
          input: 'var(--bg-input)',
          pill: 'var(--bg-pill)',
          pillHover: 'var(--bg-pill-hover)',
        },
        fg: {
          DEFAULT: 'var(--fg)',
          heading: 'var(--fg-heading)',
          secondary: 'var(--fg-secondary)',
          muted: 'var(--fg-muted)',
          faint: 'var(--fg-faint)',
          price: 'var(--fg-price)',
          link: 'var(--fg-link)',
          dark: '#1b1c19',
        },
        border: {
          DEFAULT: 'var(--border)',
          light: 'var(--border-light)',
          active: 'var(--border-active)',
          accent: 'var(--border-active)',
        },
        gold: {
          DEFAULT: '#54512d',
          soft: '#6d6943',
          muted: '#8c8758',
          dark: '#3f3d22',
          faint: 'rgba(84, 81, 45, 0.1)',
        },
        status: {
          success: '#2e7d32',
          warning: '#e65100',
          error: '#ba1a1a',
          info: '#0288d1',
        },
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        '2xl': '2rem',
        '3xl': '2.5rem',
        full: '9999px',
      },
      boxShadow: {
        sm: '0 2px 8px -1px rgba(72, 55, 47, 0.06)',
        md: '0 8px 24px -4px rgba(72, 55, 47, 0.08), 0 2px 6px -1px rgba(72, 55, 47, 0.04)',
        lg: '0 16px 36px -4px rgba(72, 55, 47, 0.12), 0 4px 12px -2px rgba(72, 55, 47, 0.06)',
        paper: '0 12px 32px -4px rgba(72, 55, 47, 0.08), 0 4px 12px -2px rgba(72, 55, 47, 0.04)',
        glow: '0 0 24px rgba(84, 81, 45, 0.2)',
        'glow-sm': '0 0 12px rgba(84, 81, 45, 0.15)',
        'glow-mauve': '0 0 20px rgba(128, 94, 109, 0.25)',
      },
      animation: {
        'fade-up': 'fadeUp 0.5s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'fade-in': 'fadeIn 0.4s ease forwards',
        'scale-in': 'scaleIn 0.35s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'ticker': 'ticker 32s linear infinite',
        'pulse-subtle': 'pulseSubtle 3s ease-in-out infinite',
      },
      keyframes: {
        fadeUp: {
          from: { opacity: '0', transform: 'translateY(16px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        scaleIn: {
          from: { opacity: '0', transform: 'scale(0.97)' },
          to: { opacity: '1', transform: 'scale(1)' },
        },
        ticker: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        pulseSubtle: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.6' },
        },
      },
    },
  },
  plugins: [],
};

export default config;